name: main

on: [push, pull_request]

jobs:
    workdir:
        name: "Prepare working directory"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        steps:
            - uses: actions/checkout@v2
            # Copy & paste from https://github.com/actions/cache/blob/master/examples.md#php---composer
            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - run: composer install
            - name: Remove development docker-compose override
              run: rm docker-compose.override.yml
            - name: Create tarball
              run: tar -czpf /tmp/workdir.tar.gz . && mv /tmp/workdir.tar.gz .
            - name: Upload workdir
              uses: actions/upload-artifact@v1
              with:
                  name: workdir
                  path: workdir.tar.gz

    tests-unit:
        name: "Run unit tests"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: phing tests-unit

    tests-integrations:
        name: "Run integration tests"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir

        services:
            smtp-hospodareni.loc:
                image: tophfr/mailcatcher:0.6.5_3
                env:
                    SMTP_HOST: smtp-hospodareni.loc
            mysql-test:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: 'root'
                    MYSQL_DATABASE: hskauting
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: phing tests-integration

    tests-acceptance:
        name: "Run acceptance tests"
        runs-on: ubuntu-18.04
        needs: workdir
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - name: Start application containers
              run: docker-compose up -d
            - run: mv app/config/config.ci.local.neon app/config/config.local.neon
            - name: Setup correct file permissions
              run: docker-compose exec -T app bash -c 'chown www-data:www-data . -R; chmod 777 . -R'
            - name: Prepare database
              run: docker-compose exec -T -u www-data app php www/index.php migrations:migrate --no-interaction
            - name: Install Node.js
              uses: actions/setup-node@v1
            - run: npm install -g yarn
            - name: Build frontend assets
              run: yarn install && yarn build
            - run: docker-compose exec -T -u www-data app phing tests-acceptance

    static-analysis:
        name: "Run PHPStan analysis"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: phing static-analysis

    coding-standard:
        name: "Check coding standard"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: phing coding-standard

    latte-lint:
        name: "Lint Latte templates"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir
        env:
            DEVELOPMENT_MACHINE: true
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: mv app/config/config.ci.local.neon app/config/config.local.neon
            - run: php www/index.php app:lint-latte

    validate-mapping:
        name: "Validate mapping against migrations"
        runs-on: ubuntu-18.04
        container:
            image: fmasa/lebeda:7.4
        needs: workdir
        services:
            mysql-test:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: 'root'
                    MYSQL_DATABASE: hskauting
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
            DEVELOPMENT_MACHINE: true
        steps:
            - name: Download workdir
              uses: actions/download-artifact@v1
              with:
                  name: workdir
                  path: .
            - name: Extract workdir
              run: tar -xzf workdir.tar.gz
            - run: mv app/config/config.ci.local.neon app/config/config.local.neon
            - run: php www/index.php migrations:migrate --no-interaction
            - run: "! php www/index.php migrations:diff && php www/index.php migrations:diff --allow-empty-diff"
